"""Representative regression samples for the generic coastal preview engine."""

REGRESSION_SAMPLES = [
    {
        "id": "bondi_open_coast",
        "lat": -33.8915,
        "lon": 151.2767,
        "expected_status": "ok",
        "archetype": "open_coast",
        "sample_type": "public_reference",
        "selection_reason": "Well-known exposed surf coastline reference for generic open-coast behavior.",
    },
    {
        "id": "manly_open_coast",
        "lat": -33.7950,
        "lon": 151.2870,
        "expected_status": "ok",
        "archetype": "open_coast",
        "sample_type": "public_reference",
        "selection_reason": "Second open-coast sample to avoid overfitting open-coast behavior to one beach.",
    },
    {
        "id": "bare_island_rock_edge",
        "lat": -33.9904,
        "lon": 151.2305,
        "expected_status": "ok",
        "archetype": "rocky_open_edge",
        "sample_type": "public_reference",
        "selection_reason": "Open rocky edge case used to keep rock-like signals alive beside surf-style beaches.",
    },
    {
        "id": "sydney_harbour_edge",
        "lat": -33.8523,
        "lon": 151.2108,
        "expected_status": "ok",
        "archetype": "sheltered_edge",
        "sample_type": "public_reference",
        "selection_reason": "Sheltered urban harbour edge reference for bay and access-style behavior.",
    },
    {
        "id": "hobart_tidal",
        "lat": -42.8821,
        "lon": 147.3390,
        "expected_status": "ok",
        "archetype": "tidal_edge",
        "sample_type": "public_reference",
        "selection_reason": "Tidal-water sample that is clearly supported but should stay generic and low-confidence.",
    },
    {
        "id": "fremantle_harbour",
        "lat": -32.0565,
        "lon": 115.7426,
        "expected_status": "ok",
        "archetype": "harbour_mixed",
        "sample_type": "public_reference",
        "selection_reason": "Harbour-mixed access case with both exposed and structured shoreline cues.",
    },
    {
        "id": "cronulla_beach",
        "lat": -34.0588,
        "lon": 151.1575,
        "expected_status": "ok",
        "archetype": "surf_coast",
        "sample_type": "public_reference",
        "selection_reason": "Surf-oriented coast sample used to validate the surf_coast preset.",
    },
    {
        "id": "newcastle_harbour",
        "lat": -32.9267,
        "lon": 151.7800,
        "expected_status": "ok",
        "archetype": "harbour_access",
        "sample_type": "public_reference",
        "selection_reason": "Harbour access sample chosen to lift jetty and access-style signals over beach-first bias.",
    },
    {
        "id": "geelong_bay_edge",
        "lat": -38.1485,
        "lon": 144.3613,
        "expected_status": "ok",
        "archetype": "bay_edge",
        "sample_type": "public_reference",
        "selection_reason": "Sheltered bay-edge sample for broad inshore and bay-coast behavior.",
    },
    {
        "id": "st_kilda_bay",
        "lat": -37.8676,
        "lon": 144.9730,
        "expected_status": "ok",
        "archetype": "bay_edge",
        "sample_type": "public_reference",
        "selection_reason": "Second bay-edge sample to keep bay behavior from collapsing to one geography.",
    },
    {
        "id": "port_arthur_open",
        "lat": -43.1510,
        "lon": 147.8500,
        "expected_status": "ok",
        "archetype": "open_coast",
        "sample_type": "public_reference",
        "selection_reason": "Southern exposed coast sample to diversify open-coast behavior beyond Sydney.",
    },
    {
        "id": "port_hacking_edge",
        "lat": -34.0700,
        "lon": 151.1230,
        "expected_status": "ok",
        "archetype": "harbour_mixed",
        "sample_type": "public_reference",
        "selection_reason": "Mixed estuary-harbour edge sample for structured but still coastal access behavior.",
    },
    {
        "id": "bruny_channelish",
        "lat": -43.2360,
        "lon": 147.3440,
        "expected_status": "ok",
        "archetype": "channel_mixed",
        "sample_type": "public_reference",
        "selection_reason": "Channel-like mixed water sample kept after testing showed it was not a pure estuary-edge case.",
    },
    {
        "id": "devonport_edge",
        "lat": -41.1760,
        "lon": 146.3600,
        "expected_status": "ok",
        "archetype": "harbour_access",
        "sample_type": "public_reference",
        "selection_reason": "Additional harbour-access case to broaden structured shoreline coverage.",
    },
    {
        "id": "port_river_mid",
        "lat": -34.8200,
        "lon": 138.5000,
        "expected_status": "ok",
        "archetype": "harbour_access",
        "sample_type": "public_reference",
        "selection_reason": "Port-river style access sample to test structured tidal access close to supported water.",
    },
    {
        "id": "botany_bay_inner",
        "lat": -33.9900,
        "lon": 151.1800,
        "expected_status": "ok",
        "archetype": "harbour_mixed",
        "sample_type": "public_reference",
        "selection_reason": "Inner bay sample used to widen sheltered harbour and bay access coverage.",
    },
    {
        "id": "darwin_harbour_inner",
        "lat": -12.4400,
        "lon": 130.8400,
        "expected_status": "ok",
        "archetype": "harbour_access",
        "sample_type": "public_reference",
        "selection_reason": "Tropical inner-harbour sample used to diversify harbour-access behavior geographically.",
    },
    {
        "id": "pittwater_inner",
        "lat": -33.6200,
        "lon": 151.3100,
        "expected_status": "ok",
        "archetype": "harbour_access",
        "sample_type": "public_reference",
        "selection_reason": "Inner waterway access case used to broaden harbour-access regression coverage.",
    },
    {
        "id": "moreton_bay_inner",
        "lat": -27.3300,
        "lon": 153.1700,
        "expected_status": "ok",
        "archetype": "large_bay_mixed",
        "sample_type": "public_reference",
        "selection_reason": "Large bay sample used to track mixed open-water and sheltered-bay signals outside southern states.",
    },
    {
        "id": "georges_river_inner_near",
        "lat": -33.9800,
        "lon": 151.0800,
        "expected_status": "ok",
        "archetype": "tidal_edge",
        "sample_type": "public_reference",
        "selection_reason": "Near-water inner estuary sample used to compare direct support against extended corridor support.",
    },
    {
        "id": "gold_coast_inland_boundary",
        "lat": -28.0167,
        "lon": 153.4000,
        "expected_status": "ok",
        "archetype": "boundary_near_coast",
        "sample_type": "boundary_probe",
        "selection_reason": "Hand-picked inland-near-coast boundary that should still keep a cautious preview.",
    },
    {
        "id": "georges_river_inner_corridor",
        "lat": -33.9000,
        "lon": 151.0800,
        "expected_status": "ok",
        "archetype": "tidal_corridor",
        "sample_type": "scanned_candidate",
        "selection_reason": "Selected after local coordinate scanning to exercise the extended tidal-corridor preview path.",
    },
    {
        "id": "surfers_inland_farther",
        "lat": -28.0300,
        "lon": 153.3800,
        "expected_status": "unsupported",
        "archetype": "boundary_reject",
        "sample_type": "boundary_probe",
        "selection_reason": "Hand-picked near-coast inland point that should now be rejected by the tighter support boundary.",
    },
    {
        "id": "adelaide_inner_far",
        "lat": -34.9285,
        "lon": 138.6007,
        "expected_status": "unsupported",
        "archetype": "boundary_reject",
        "sample_type": "boundary_probe",
        "selection_reason": "Urban inland point near broad coastal water that should not get a generic preview.",
    },
    {
        "id": "brisbane_river_inner_far",
        "lat": -27.4705,
        "lon": 153.0260,
        "expected_status": "unsupported",
        "archetype": "boundary_reject",
        "sample_type": "boundary_probe",
        "selection_reason": "Inner-city river sample used to reject overly permissive far-inland preview behavior.",
    },
    {
        "id": "swan_inner_far",
        "lat": -31.9700,
        "lon": 115.8500,
        "expected_status": "unsupported",
        "archetype": "boundary_reject",
        "sample_type": "boundary_probe",
        "selection_reason": "Far-inner estuary candidate used to confirm the extended corridor band stays narrow.",
    },
    {
        "id": "launceston_inner_reject",
        "lat": -41.4332,
        "lon": 147.1441,
        "expected_status": "unsupported",
        "archetype": "inland_reject",
        "sample_type": "boundary_probe",
        "selection_reason": "Northern Tasmania inland-water reference used to avoid extending v1 into non-coastal inland forecasts.",
    },
    {
        "id": "alice_springs_inland",
        "lat": -23.6980,
        "lon": 133.8807,
        "expected_status": "unsupported",
        "archetype": "inland_reject",
        "sample_type": "public_reference",
        "selection_reason": "Clear inland control sample for obvious unsupported behavior.",
    },
    {
        "id": "wagga_inland",
        "lat": -35.1082,
        "lon": 147.3598,
        "expected_status": "unsupported",
        "archetype": "inland_reject",
        "sample_type": "public_reference",
        "selection_reason": "Second inland control sample to avoid relying on a single unsupported inland reference.",
    },
]
